%
% FILE NAME:    masterScriptRatGEM.m
%
% PURPOSE: This script is for reconstruction of the Rat-GEM, by using
%          the Human-GEM as template and taking into account rat-specific
%          pathways/reactions.
%
%          Annotation files in tsv format are also generated by
%          integrating human and rat-specific annotation information.
%


%% Add path
addpath(genpath('../../Rat-GEM/'));


%% Prepare Rat ortholog pairs and species-specific network

% get ortholog pairs from human to rat
ratOrthologPairs = extractAllianceGenomeOrthologs('human2RatOrthologs.json');

% load species-specific rxns and mets
rxnsToAdd = importTsvFile('ratSpecificRxns.tsv');
metsToAdd = importTsvFile('ratSpecificMets.tsv');


%% Generate Rat-GEM
[ratGEM, speciesSpecNetwork, gapfillNetwork]=updateAnimalGEM(...
    ratOrthologPairs,rxnsToAdd,metsToAdd,'Rat-GEM');


%% Update annotations
[rxnAssoc, metAssoc] = updateAnimalAnnotations(ratGEM,rxnsToAdd,metsToAdd);


%% Save annotation into tsv files, and the model into mat, yml, and xml

% sanity check
if isequal(rxnAssoc.rxns, ratGEM.rxns) && isequal(metAssoc.mets, ratGEM.mets)
	fprintf('sanity check passed.\n');
    exportTsvFile(rxnAssoc,'../model/reactions.tsv');
    exportTsvFile(metAssoc,'../model/metabolites.tsv');
end

ratGEM = annotateGEM(ratGEM,'../model',{'rxn','met'});  % add annotation data to structure
ratGEM.id = regexprep(ratGEM.id,'-','');  % remove dash from model ID since it causes problems with SBML I/O
save('../model/Rat-GEM.mat', 'ratGEM');
exportYaml(ratGEM, '../model/Rat-GEM.yml');
exportModel(ratGEM, '../model/Rat-GEM.xml');


